Helpers functions test and fix
UmbrellaLeaf5/locus_no_pilotus pull request #63
Opened 2024-04-27 11:29 UTC by Stargazer2005

- Add tests for helper functions in lib/math
- Fix and beautify some of them
- NEEDFIX: There is a problem with template function TangentBetween() for poly with another obstacle

2024-05-02 16:45 UTC, Stargazer2005 commented on math/optimal_way/helpers_functions.cpp
> +      (-((a / b) * ((c / b) + y_1) - x_1)) / (1 + (pow(a, 2) / pow(b, 2)));
а разве не возникнет проблемы с b = 0?

2024-05-02 16:46 UTC, Stargazer2005 commented on math/optimal_way/helpers_functions.cpp
> +      (-((a / b) * ((c / b) + y_1) - x_1)) / (1 + (pow(a, 2) / pow(b, 2)));
будут nan получаться

2024-05-02 18:42 UTC, Stargazer2005 commented on tests/maths/are_there_intersections.cpp
> +}
Можешь сделать тесты показательными разбиением на 3 подгруппы:
1)пересечение и отрезком, и прямой, на которой он лежит
2) пересечение прямой, но не отрезком
3) отсутствия пересечения прямой и, следовательно, отрезком

2024-05-02 18:43 UTC, Romanov-Fedor commented on math/optimal_way/helpers_functions.cpp
> +      (-((a / b) * ((c / b) + y_1) - x_1)) / (1 + (pow(a, 2) / pow(b, 2)));
А, да, это откатить надо, согласен

2024-05-02 19:22 UTC, UmbrellaLeaf5 requested changes
чекните варнинги мерджем из main и пофиксите их

2024-05-02 19:22 UTC, UmbrellaLeaf5 commented on math/optimal_way/helpers_functions.cpp
> +  double theta = acos(radius / dist);
ну вы и греки
а можно комментарий, за что такое название угла отвечает?)

2024-05-02 19:22 UTC, UmbrellaLeaf5 commented on math/optimal_way/helpers_functions.cpp
кста, советую мердж от main сделать и чекнуть, какие весёлые варнинги у вас падают))

2024-05-02 19:22 UTC, UmbrellaLeaf5 commented on math/optimal_way/helpers_functions.cpp
> +  std::size_t prev = -1;
а это не UB? size_t = unsigned long long int XXXXDD

2024-05-02 19:22 UTC, UmbrellaLeaf5 commented on math/optimal_way/helpers_functions.h
> + * @brief Находит точки касания двух многугольников с их общей
у вас автоматически так комменты doxygen переносятся?

2024-05-02 19:30 UTC, Stargazer2005 commented on math/optimal_way/helpers_functions.h
> + * @brief Находит точки касания двух многугольников с их общей
да

2024-05-03 10:38 UTC, UmbrellaLeaf5 approved these changes

2024-05-03 10:38 UTC, merged